### ISSUE TITLE
Any ideas on how to compile this to a .node file?

### ISSUE THREAD

**Issue by fridgerator** [jeromegn/v8.cr#2]
Rust Neon is doing it : https://github.com/neon-bindings/neon

It *seems* like they are compiling an object file and then somehow linking it with node-gyp.

**Comment by fridgerator** [comment]
Nvmd, looks like they are they are compiling the rust to a dylib and then linking it: https://github.com/neon-bindings/neon/blob/master/cli/src/project.ts#L24

Dont think this will be possible with crystal right now

**Comment by jeromegn** [comment]
If it's possible to compile a Crystal program as a dynamic lib, then it might be possible.

However, this crate only deal with raw V8. There's no knowledge of node.js. It's also a very alpha, barebones, implementation.

This is based on the golang v8 bindings, but I've since decided this was the wrong way to go. Message passing is easier to deal with and reduces the FFI surface area.

Another concern is Crystal uses fibers extensively for concurrency. V8 does not like fibers at all, segfaults happen very quickly if fibers are used. Something to do with how V8 does stacks.
